/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://q4crcnj5s5c3tosckyolubokkq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w7mdkuohvbb6ldkmj3qcl56vze",
    "aws_cognito_identity_pool_id": "ap-south-1:dc3d3ded-29b1-46af-bd09-6824788445cf",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_orak4GvUY",
    "aws_user_pools_web_client_id": "17i32s8le6d4c0omoc4srub3mg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifynext5817ad19a6054f3481ad74db6c00998f131334-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
