/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://nzs3gquizfespcho2dtkljzvie.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6ebkrgmm4jejzfezygvmhy34wy",
    "aws_cognito_identity_pool_id": "ap-south-1:a8cba7dd-65fe-4e7c-b959-03195bcfe464",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_6hl0o1MDu",
    "aws_user_pools_web_client_id": "7cp4lab6l09r2icpj1uf6446ec",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifynext5817ad19a6054f3481ad74db6c00998f71351-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
