import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { DataStore } from "aws-amplify";
import { Post } from '../models';
import List from '../components/List';

export async function getStaticProps() {
  const data = await DataStore.query(Post);
  const posts = await JSON.parse(JSON.stringify(data));
  return {
    props: { posts },
  }
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        posts && posts.map((post) => (
          <List key={post.id} data={post} />
        ))
      }
    </div>
  )
}
