import Head from 'next/head'
import { DataStore } from "aws-amplify";
import { Post, Link } from '../models';
import List from '../components/List';
import Header from '../components/Header';

export async function getStaticProps() {
  const dataPost = await DataStore.query(Post);
  const dataLink = await DataStore.query(Link);
  const posts = await JSON.parse(JSON.stringify(dataPost));
  const links = await JSON.parse(JSON.stringify(dataLink));
  return {
    props: { posts, links },
  }
}

export default function Home({ posts, links }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header data={links} />
      <div className='w-4/5 mx-auto mt-5 flex justify-start items-start flex-wrap gap-5'>
        {
          posts && posts.map((post) => {
            return (
              <List key={post.id} data={post} />
            )
          })
        }
      </div>
    </div>
  )
}
